"""PDF Forensic Report Generator.

Generates comprehensive PDF reports with:
  - Executive summary (LLM-narrated or template)
  - Per-engine findings with embedded charts
  - Flagged entities tables
  - Methodology section
  - Evidence chain
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch, mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, Image,
)

from services.llm_narrator import generate_narrative

logger = logging.getLogger(__name__)

# Colors matching frontend theme
DARK_BG = colors.HexColor("#0a0a0f")
CARD_BG = colors.HexColor("#1a1a2e")
PRIMARY = colors.HexColor("#00d4ff")
DANGER = colors.HexColor("#ff4757")
WARNING = colors.HexColor("#ffa502")
SUCCESS = colors.HexColor("#2ed573")
TEXT_COLOR = colors.HexColor("#333333")
BORDER_COLOR = colors.HexColor("#dddddd")


async def generate_report(
    analysis_id: str,
    exam_name: str,
    total_students: int,
    total_centers: int,
    overall_score: float,
    engine_data: dict[str, dict[str, Any]],
    output_path: Path,
) -> Path:
    """Generate a comprehensive PDF forensic report."""
    logger.info(f"Generating PDF report for analysis {analysis_id}")

    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        "CustomTitle", parent=styles["Title"],
        fontSize=24, spaceAfter=20, textColor=PRIMARY,
    )
    heading_style = ParagraphStyle(
        "CustomHeading", parent=styles["Heading1"],
        fontSize=16, spaceBefore=20, spaceAfter=10, textColor=TEXT_COLOR,
    )
    subheading_style = ParagraphStyle(
        "CustomSubheading", parent=styles["Heading2"],
        fontSize=13, spaceBefore=12, spaceAfter=8,
    )
    body_style = ParagraphStyle(
        "CustomBody", parent=styles["Normal"],
        fontSize=10, spaceAfter=8, leading=14,
    )
    small_style = ParagraphStyle(
        "Small", parent=styles["Normal"],
        fontSize=8, textColor=colors.gray,
    )

    doc = SimpleDocTemplate(
        str(output_path),
        pagesize=A4,
        topMargin=20*mm,
        bottomMargin=20*mm,
        leftMargin=20*mm,
        rightMargin=20*mm,
    )

    story = []

    # ── Title Page ──
    story.append(Spacer(1, 50))
    story.append(Paragraph("EXAMGUARD", title_style))
    story.append(Paragraph("AI Forensic Intelligence Report", heading_style))
    story.append(Spacer(1, 20))
    story.append(Paragraph(f"<b>Examination:</b> {exam_name}", body_style))
    story.append(Paragraph(f"<b>Analysis ID:</b> {analysis_id[:8]}...", body_style))
    story.append(Paragraph(f"<b>Total Students:</b> {total_students:,}", body_style))
    story.append(Paragraph(f"<b>Total Centers:</b> {total_centers}", body_style))
    story.append(Paragraph(f"<b>Overall Integrity Score:</b> {overall_score:.1f}/100", body_style))

    score_color = DANGER if overall_score < 50 else WARNING if overall_score < 75 else SUCCESS
    score_text = "COMPROMISED" if overall_score < 50 else "SUSPICIOUS" if overall_score < 75 else "ACCEPTABLE"
    story.append(Paragraph(
        f'<font color="{score_color.hexval()}">'
        f'<b>Assessment: {score_text}</b></font>',
        ParagraphStyle("Score", parent=body_style, fontSize=14),
    ))

    story.append(Spacer(1, 20))
    story.append(Paragraph(
        "<i>This report was generated by ExamGuard — an AI forensic analysis platform. "
        "All fraud detection is performed using mathematical and machine learning algorithms. "
        "Report narratives are generated by a local LLM (Mistral 7B) for readability.</i>",
        small_style,
    ))
    story.append(PageBreak())

    # ── Executive Summary ──
    story.append(Paragraph("1. Executive Summary", heading_style))

    total_flagged = sum(d.get("flagged_count", len(d.get("flagged_student_ids", [])))
                       for d in engine_data.values()
                       if isinstance(d, dict))

    exec_summary = await generate_narrative("executive_summary", {
        "total_students": total_students,
        "total_centers": total_centers,
        "integrity_score": overall_score,
        "total_flagged": total_flagged,
        "engines_with_findings": ", ".join(
            k for k, v in engine_data.items()
            if isinstance(v, dict) and v.get("flagged_count", len(v.get("flagged_student_ids", []))) > 0
        ),
    })
    story.append(Paragraph(exec_summary, body_style))
    story.append(Spacer(1, 10))

    # ── Summary Table ──
    summary_data = [["Engine", "Status", "Flagged", "Key Finding"]]
    engine_display = {
        "copy_ring": ("E1: Copy Ring", "MinHash + Louvain"),
        "stat_impossibility": ("E2: Statistical Proof", "Binomial + Bonferroni"),
        "center_anomaly": ("E3: Center Anomaly", "Isolation Forest"),
        "leak_signature": ("E4: Leak Signature", "IRT + Difficulty Curve"),
        "response_time": ("E5: Response Time", "KDE + K-Means"),
        "gnn_copy_ring": ("E6: GNN", "GraphSAGE"),
        "vae_anomaly": ("E7: VAE", "Variational Autoencoder"),
        "question_similarity": ("E8: NLP", "Sentence Transformer"),
        "xgboost_ensemble": ("Ensemble", "XGBoost Meta-Classifier"),
    }

    for engine_name, (display, method) in engine_display.items():
        data = engine_data.get(engine_name, {})
        flagged = data.get("total_flagged", data.get("flagged_count",
                   len(data.get("flagged_student_ids", []))))
        summary = data.get("summary", {})
        key_finding = ""
        if isinstance(summary, dict):
            for k, v in list(summary.items())[:1]:
                key_finding = f"{k}: {v}"
        summary_data.append([display, method, str(flagged), key_finding[:50]])

    table = Table(summary_data, colWidths=[120, 120, 60, 200])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), PRIMARY),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.5, BORDER_COLOR),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8f8f8")]),
        ("ALIGN", (2, 0), (2, -1), "CENTER"),
    ]))
    story.append(table)
    story.append(PageBreak())

    # ── Per-Engine Findings ──
    story.append(Paragraph("2. Detection Engine Findings", heading_style))

    # E1: Copy Ring
    e1_data = engine_data.get("copy_ring", {})
    if e1_data:
        story.append(Paragraph("2.1 Copy Ring Detection (Engine 1)", subheading_style))
        narrative = await generate_narrative("copy_ring", {
            "clusters_found": e1_data.get("clusters_found", 0),
            "flagged_count": e1_data.get("total_flagged_students", 0),
            "largest_cluster_size": max((c.get("size", 0) for c in e1_data.get("clusters", [])), default=0),
            "avg_waa": sum(c.get("avg_waa", 0) for c in e1_data.get("clusters", [])) / max(len(e1_data.get("clusters", [])), 1),
        })
        story.append(Paragraph(narrative, body_style))

    # E4: Leak Signature
    e4_data = engine_data.get("leak_signature", {})
    if e4_data and e4_data.get("leak_detected"):
        story.append(Paragraph("2.2 Paper Leak Signature (Engine 4)", subheading_style))
        narrative = await generate_narrative("leak_signature", {
            "leaked_group_size": e4_data.get("leaked_group_size", 0),
            "leaked_questions": e4_data.get("leaked_questions", "N/A"),
            "normal_gradient": e4_data.get("gradient_stats", {}).get("normal_mean_gradient", -0.3),
            "leaked_gradient": e4_data.get("gradient_stats", {}).get("flagged_mean_gradient", 0),
        })
        story.append(Paragraph(narrative, body_style))

    # E3: Center Anomaly
    e3_data = engine_data.get("center_anomaly", {})
    if e3_data:
        story.append(Paragraph("2.3 Center Anomaly Analysis (Engine 3)", subheading_style))
        narrative = await generate_narrative("center_anomaly", {
            "anomalous_count": e3_data.get("anomalous_centers", 0),
            "worst_center": (e3_data.get("centers", [{}])[0].get("center_id") if e3_data.get("centers") else "N/A"),
        })
        story.append(Paragraph(narrative, body_style))

    story.append(PageBreak())

    # ── Methodology ──
    story.append(Paragraph("3. Methodology", heading_style))
    story.append(Paragraph(
        "ExamGuard employs a 4-layer hybrid architecture combining classical statistical methods, "
        "deep learning, machine learning ensemble, and natural language generation. "
        "All fraud detection is performed through mathematical algorithms — the LLM component "
        "is used exclusively for report narration, not detection.",
        body_style,
    ))
    story.append(Paragraph(
        "<b>Layer 1 — Classical Detection (CPU):</b> Five engines using graph theory, probability theory, "
        "anomaly detection, Item Response Theory, and statistical hypothesis testing.",
        body_style,
    ))
    story.append(Paragraph(
        "<b>Layer 2 — Deep Learning (GPU):</b> Three engines using Graph Neural Networks (GraphSAGE), "
        "Variational Autoencoders, and Sentence Transformers for pattern detection beyond rule-based methods.",
        body_style,
    ))
    story.append(Paragraph(
        "<b>Layer 3 — Meta-Ensemble (GPU):</b> XGBoost gradient boosting classifier combining all 8 "
        "engine outputs into a calibrated fraud probability per student.",
        body_style,
    ))
    story.append(Paragraph(
        "<b>Layer 4 — Forensic Narrator:</b> Local LLM (Mistral 7B via Ollama) generates human-readable "
        "report narratives from structured detection data.",
        body_style,
    ))

    story.append(Spacer(1, 20))
    story.append(Paragraph(
        "<i>Report generated by ExamGuard v2.0 — AI Forensic Intelligence for Examination Integrity</i>",
        small_style,
    ))

    # Build PDF
    doc.build(story)
    logger.info(f"PDF report saved to {output_path}")
    return output_path
